apps/belt_exam/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index),
    url(r'home$', home, name='home'),
    url(r'register$', register, name='register'),
    url(r'login$', login, name='login'),
    url(r'logout$', logout, name='logout'),
    url(r'^add/(?P<quote_id>\d+)$', add, name='add'),
    url(r'^create/$', create, name='create'),
    url(r'^drop/(?P<quote_id>\d+)$', drop, name='drop'),
    url(r'^show_user/(?P<user_id>[0-9]+)$', show_user, name='show_user')
]

belt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^',include('apps.belt_exam.urls', namespace='belt_exam'))
]

apps/belt_exam/models.py
from __future__ import unicode_literals
from collections import defaultdict, deque
from django.db import models
from django.contrib import messages
from datetime import datetime
import codecs
import random
import bcrypt
import re

class UserManager(models.Manager):
    def register(self, request):
        name = request.POST['reg_name']
        alias = request.POST['reg_alias']
        email = request.POST['email']
        reg_password = request.POST['reg_password']
        reg_password2 = request.POST['reg_password2']
        today = datetime.today()
        regex = r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"
        valid = True

        if not name:
            messages.warning(request, "Name cannot be blank.")
            valid = False
        if not alias:
            messages.warning(request, "Alias cannot be blank.")
            valid = False
        if not re.match(regex, email):
            messages.warning(request, "Invalid Email.")
            valid = False
        if len(reg_password) < 8:
            messages.warning(request, "Password must be longer than 8 characters.")
            valid = False
        if reg_password != reg_password2:
            messages.warning(request, "Passwords do not match")
            valid = False
        if not request.POST['birthdate']:
            messages.warning(request, "The Birthdate cannot be blank")
        else:
            birthdate = datetime.strptime(request.POST['birthdate'], '%Y-%m-%d')
            if (birthdate.year + 13, birthdate.month, birthdate.day) > (today.year, today.month, today.day):
                messages.warning(request, "You must be at least 13 to register!")
                valid = False
        if User.objects.filter(alias = alias):
            messages.warning(request, "Alias is already taken.")
            valid = False
        if User.objects.filter(email = email):
            messages.warning(request, "You have registered with this email before, Please login.")
            valid = False
        if valid == True:
                hashedpw = bcrypt.hashpw(reg_password.encode('UTF-8'), bcrypt.gensalt())
                makeuser = User.objects.create(name = name, alias = alias, email = email, birthdate= birthdate, password = hashedpw)
                return makeuser
                messages.success(request, "You have successfully registered, please Login.")
        return False


    def userLogin(self, request):
        email = request.POST['email']
        loginpassword = request.POST['password']
        valid = False

        if len(email) < 1:
            messages.warning(request, "Email cannot be blank!")
            return False
        if len(loginpassword) < 1:
            messages.warning(request, "Password cannot be blank!")
            return False
        try:
            user = User.objects.get(email = email)
        except:
            messages.warning(request, "User does not exist!")
            return False
        if bcrypt.hashpw(loginpassword.encode(), user.password.encode()) == user.password.encode():

            request.session['user_id'] = user.id
            request.session['name'] = user.name
            return True
        else:
            messages.warning(request, "Password is incorrect!")
            return False



class User(models.Model):
      name = models.CharField(max_length=45, default='')
      alias = models.CharField(max_length=45, default='')
      email = models.CharField(max_length=45, default='')
      password = models.CharField(max_length=200, default='')
      birthdate = models.DateField()
      created_at = models.DateTimeField(auto_now_add=True)
      updated_at = models.DateTimeField(auto_now=True)
      objects = UserManager()

class Quote(models.Model):
    name = models.CharField(max_length=64)
    message = models.CharField(max_length=255)
    posted_by = models.ForeignKey(User, related_name='all_quotes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Favorite(models.Model):
    quote = models.ForeignKey(Quote, related_name='quote_favorites')
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/belt_exam/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import UserManager, User, Quote, Favorite

def index(request):
    if 'user_id' not in request.session:
        request.session['user_id'] = 0
    return render(request, 'belt_exam/index.html')

def register(request):
    if User.objects.register(request):
        return redirect('belt_exam:home')
    else:
        return redirect('/')

def login(request):
    if User.objects.userLogin(request):
        return redirect('belt_exam:home')
    else:
        return redirect('/')

def home(request):
    users = User.objects.all()
    try:
        User.objects.get(id = request.session['user_id'])
    except:
        return redirect('/')
    new_user = User.objects.get(id = request.session['user_id'])
    user = User.objects.get(id = request.session['user_id'])
    user_id = request.session['user_id']
    context = {
    'user': user,
    'new_user' : User.objects.get(id=request.session['user_id']),
    'all_quotes' : Quote.objects.all().order_by('-created_at'),
    'my_favorite' : Favorite.objects.filter(user_id=user_id).order_by('-created_at')
        }
    return render(request, 'belt_exam/home.html', context)

def add(request, quote_id):
    new_user = User.objects.get(id=request.session['user_id'])
    new_quote = Quote.objects.get(id=quote_id)
    Favorite.objects.create(user=new_user, quote=new_quote)
    return redirect('belt_exam:home')

def drop(request, quote_id):
    user_id = request.session['user_id']
    Favorite.objects.filter(user=user_id, quote=quote_id).delete()
    return redirect('belt_exam:home')

def show_user(request, user_id):
    new_user = User.objects.get(id=user_id)
    my_quotes = Quote.objects.filter(posted_by=user_id)

    context = {
    'user' : new_user,
    'my_quotes': my_quotes
    }
    return render(request, 'belt_exam/users.html', context)

def create(request):
    name = request.POST['name']
    message = request.POST['message']
    user = User.objects.get(id=request.session['user_id'])
    if len(name) < 3:
        messages.add_message(request, messages.ERROR, 'Quoted by should be more than 3 characters')
    if len(message) < 10:
        messages.add_message(request, messages.ERROR, 'Message should be more than 10 characters')
    else:
        Quote.objects.create(name=name, message=message, posted_by=user)
    return redirect('belt_exam:home')


def logout(request):
    request.session.delete()
    return redirect('/')

apps/belt_exam/templates/belt_exam/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> Home</title>
    {% load staticfiles %}
  </head>
  <body>
      {% if request.session.user_id %}

      <h1>Welcome, {{user.name}}</h1>

    <h3>Contribute a Quote: </h3>

    <form action="{% url 'belt_exam:create' %}"method="post">
            {% csrf_token %}
        <label for="name">Quoted By: </label>
        <input type="text" name="name"><br><br>
        <label for="">Message: </label>
        <textarea name="message" rows="8" cols="50"></textarea><br><br>
        <input type="submit" value="Submit Quote">
    </form>
    <hr> {% for m in messages %}
    <p>{{m}}</p>
    {% endfor %}


      <h2> Quotable Quotes:</h2>

      {% for quote in all_quotes %}

        <h5>Quoted By:</h5> <p>{{quote.name}}<p>
        <h5>The Quote:</h5> {{quote.message}}
        Posted by: <a href="{% url 'belt_exam:show_user' user_id=quote.posted_by.id %}">{{quote.posted_by.name}}</a>
        <td><a href="{% url 'belt_exam:add' quote_id=quote.id %}">Add to My List</a></td>
        </tr>
            {% endfor %}

      <hr>
<h2> Your Favorites</h2>
{% for favorite in my_favorite %}
  <h5>Quoted By:</h5> <p>{{favorite.quote.name}}<p>
  <h5>The Quote:</h5> {{favorite.quote.message}}
  <i>Posted by <a href="{% url 'belt_exam:add' quote_id=favorite.quote.id %}"> {{favorite.user.name}}</a></i>
					<br>
  <td><a href="{% url 'belt_exam:drop' quote_id=favorite.quote.id %}">Remove from my List</a></td>
  </tr>
      {% endfor %}

    <hr>
      <table>
          <tr>
            <th> User ID </th>
            <th> User Name </th>
            <th> Alias </th>
            <th> Email </th>
            <th> DOB </th>
        </tr>

        <tr>
          <td>{{user.id}}</td>
          <td>{{user.name}}</td>
          <td>{{user.alias}}</td>
          <td>{{user.email}}</td>
          <td>{{user.birthdate}}</td>

      </table><br>
      <hr>
{% endif %}
        <a href="/logout"> Logout </a>

  </body>
</html>

apps/belt_exam/templates/belt_exam/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> Login Page </title>

    {% load staticfiles %}
  </head>

  <body>


      <h2> Welcome! </h2>
        <h2> Login: </h2>
        <form action="{% url 'belt_exam:login' %}" method="post">{% csrf_token %}
          <p><label for='1'> Email<input type="text" name='email'></label></p>
          <p><label for='2'> Password :<input type="password" name='password'></label></p>
          <p><input type="submit" value='Login'></p>
        </form>



        <h2> Register: </h2>
        <form action="{% url 'belt_exam:register' %}" method="post">{% csrf_token %}
          <p><label for='3'> Name: <input type="text" name='reg_name'></label></p>
          <p><label for='4'> Alias: <input type="text" name='reg_alias'></label></p>
          <p><label for='4'> Email: <input type="text" name='email'></label></p>
          <p><label for='6'> Password: <input type="password" name='reg_password'></label></p>
          <h5>*Password must be longer than 8 characters</h5>
          <p><label for='7'> Confirm Password: <input type="password" name='reg_password2'></label></p>
          <p><label for='8'> Birthdate: <input type="date" name='birthdate'></label></p>
          <p><input type="submit" value='Register'></p>
        </form>

      {% if messages %}

            <ul>
                {% for message in messages %}
                  <li >{{ message }}</li>
                {% endfor %}
            </ul>
      {% endif %}

    </div>
  </body>
</html>

apps/belt_exam/templates/belt_exam/users.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Users Page</title>
        {% load staticfiles %}
    </head>
    <body>
        <h2>Posted by  {{ user.name}}</h2>
            <a href="/logout"><button type="button" name="logout">Log Out</button></a>
            <a href="/home"><button type="button" name="home">Home</button></a>

		<h2>Count: {{user.quote_count}}</h2>

		{% for quote in my_quotes %}
			<p>
			{{quote.name}}
			{{quote.message}}
			</p>
		{% endfor %}
    </body>
</html>